# Generated by Django 3.2 on 2021-05-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
