# Generated by Django 3.2 on 2021-05-02 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_auto_20210502_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='creation_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 14, 11, 18, 447876)),
        ),
        migrations.AddField(
            model_name='post',
            name='creation_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 14, 11, 18, 447445)),
        ),
    ]
