# Generated by Django 3.2 on 2021-05-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_auto_20210502_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
