# Generated by Django 3.2 on 2021-05-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0007_alter_post_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='creation_date_time',
        ),
        migrations.AddField(
            model_name='post',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='images/'),
        ),
    ]
