# Generated by Django 3.2 on 2021-05-03 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0008_auto_20210503_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creation_date',
            new_name='creation_date_time',
        ),
    ]
