# Generated by Django 3.2 on 2021-05-06 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_alter_post_post_image'),
        ('Notifications', '0002_notification_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='NotificatedPost', to='Posts.post'),
            preserve_default=False,
        ),
    ]
