# Generated by Django 3.2 on 2021-04-30 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('RecieverUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieverUser', to=settings.AUTH_USER_MODEL)),
                ('senderUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
