# Generated by Django 3.2 on 2021-05-06 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('isread', models.BooleanField(default=False)),
                ('RecieverUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieverUser', to=settings.AUTH_USER_MODEL)),
                ('senderUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isread', models.BooleanField(default=False)),
                ('room_messages', models.ManyToManyField(related_name='messages', to='Chats.Chat')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user2', 'user1'), ('user1', 'user2')},
            },
        ),
    ]
