# Generated by Django 3.2 on 2021-05-05 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chats', '0002_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='room_member',
        ),
        migrations.AddField(
            model_name='chat',
            name='isread',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='user1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='Users.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='user2',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='Users.customuser'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('RecieverUser', 'senderUser'), ('senderUser', 'RecieverUser')},
        ),
    ]
