# Generated by Django 3.2 on 2021-05-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0003_auto_20210505_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='isread',
            field=models.BooleanField(default=False),
        ),
    ]
