# Generated by Django 3.2 on 2021-05-05 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chats', '0004_alter_chat_isread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='RecieverUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recieverUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='senderUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='senderUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
