# Generated by Django 3.2 on 2021-05-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0006_auto_20210505_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='isread',
            field=models.BooleanField(default=False),
        ),
    ]
