# Generated by Django 3.2 on 2021-05-04 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='Reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieverRequest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='Sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderRequest', to=settings.AUTH_USER_MODEL),
        ),
    ]
