# Generated by Django 3.2 on 2021-05-05 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20210504_1955'),
        ('Users', '0002_auto_20210504_2215'),
    ]

    operations = [
    ]
