# Generated by Django 3.2 on 2021-05-04 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20210504_1953'),
        ('Users', '0002_auto_20210504_2215'),
    ]

    operations = [
    ]
