# Generated by Django 3.2 on 2021-05-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20210504_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_avatar',
            field=models.ImageField(default='default.png', max_length=50, upload_to='Chats/static/profile'),
        ),
    ]
