# Generated by Django 3.2 on 2021-05-05 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_merge_0002_auto_20210504_1953_0002_auto_20210504_2215'),
        ('Users', '0006_auto_20210505_0102'),
    ]

    operations = [
    ]
