# Generated by Django 3.2 on 2021-05-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_merge_20210505_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('send', 'send'), ('accepted', 'accepted'), ('cancel', 'cancel')], default=None, max_length=8),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
