# Generated by Django 3.2.1 on 2021-05-06 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20210504_1831'),
        ('Users', '0007_merge_20210505_0206'),
    ]

    operations = [
    ]
