# Generated by Django 3.2 on 2021-05-05 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_auto_20210505_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friend_id',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user_id',
        ),
        migrations.AddField(
            model_name='friend',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
