<<<<<<< HEAD
# Generated by Django 3.2.1 on 2021-05-06 19:44
=======
# Generated by Django 3.2 on 2021-05-06 08:01
>>>>>>> 183321935eb089d5402c0ac95a476c069800be88

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('Users', '0008_merge_20210506_0031'),
=======
        ('Users', '0008_merge_20210505_1713'),
>>>>>>> 183321935eb089d5402c0ac95a476c069800be88
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2021, 5, 6)),
        ),
    ]
