# Generated by Django 3.2 on 2021-05-06 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_merge_20210506_0031'),
        ('Users', '0010_auto_20210506_0042'),
    ]

    operations = [
    ]
