# Generated by Django 3.2 on 2021-05-06 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_customuser_date_of_birth'),
        ('Users', '0011_merge_20210506_0138'),
    ]

    operations = [
    ]
