# Generated by Django 3.2 on 2021-04-30 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('creation_date', models.DateField(auto_now=True)),
                ('members', models.ManyToManyField(related_name='joinedgroups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
