# Generated by Django 3.2.1 on 2021-05-06 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Groups', '0002_alter_group_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='requests',
            field=models.ManyToManyField(related_name='requestedgroups', to=settings.AUTH_USER_MODEL),
        ),
    ]
